### ISSUE TITLE
Whether the frame merging code is available?

### ISSUE THREAD

**Issue by zhanghui75** [TonyXuQAQ/CenterLineDet#7]
In segmentation_baselines directories, the baseline models (HDMapNet, FusionNet) are shared. However, it seems that the results are only for single-frame, and the multi-frame results are not available?

Specifically, I mean the frame merging code mentioned as below:
"To adapt it to our multi-frame detection task, we apply the frame merging method proposed in [25] to construct the world-level graph of lane centerlines."

**Comment by TonyXuQAQ** [comment]
Yes. Sorry that the scripts to obtain the merged segmentation results are put in ```./CenterLineDet``` instead of ```./segmentation_baselines```.

We merge adjacent frames of the segmentation results for CenterLineDet. The merge operation is only applied during inference. Please check [this function](https://github.com/TonyXuQAQ/CenterLineDet/blob/08c82a78cf9a493f0b70a3a77d6d1382d15686c7/CenterLineDet/get_frame_segmentation.py#L55). You could generate the merged segmentation results by running ```./CenterLineDet/bash/Fusion_fuse_segmentation.bash``` or ```./CenterLineDet/bash/HD_fuse_segmentation.bash```.
